// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package decktest

import (
	"github.com/ramonmedeiros/deck/internal/pkg/deck"
	"sync"
)

// ManagerMock is a mock implementation of deck.Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked deck.Manager
//		mockedManager := &ManagerMock{
//			GetFunc: func(deckID string) (*deck.Deck, error) {
//				panic("mock out the Get method")
//			},
//			NewDeckFunc: func(shuffled bool, cards ...string) (*deck.Deck, error) {
//				panic("mock out the NewDeck method")
//			},
//		}
//
//		// use mockedManager in code that requires deck.Manager
//		// and then make assertions.
//
//	}
type ManagerMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(deckID string) (*deck.Deck, error)

	// NewDeckFunc mocks the NewDeck method.
	NewDeckFunc func(shuffled bool, cards ...string) (*deck.Deck, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// DeckID is the deckID argument value.
			DeckID string
		}
		// NewDeck holds details about calls to the NewDeck method.
		NewDeck []struct {
			// Shuffled is the shuffled argument value.
			Shuffled bool
			// Cards is the cards argument value.
			Cards []string
		}
	}
	lockGet     sync.RWMutex
	lockNewDeck sync.RWMutex
}

// Get calls GetFunc.
func (mock *ManagerMock) Get(deckID string) (*deck.Deck, error) {
	callInfo := struct {
		DeckID string
	}{
		DeckID: deckID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			deckOut *deck.Deck
			errOut  error
		)
		return deckOut, errOut
	}
	return mock.GetFunc(deckID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManager.GetCalls())
func (mock *ManagerMock) GetCalls() []struct {
	DeckID string
} {
	var calls []struct {
		DeckID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// NewDeck calls NewDeckFunc.
func (mock *ManagerMock) NewDeck(shuffled bool, cards ...string) (*deck.Deck, error) {
	callInfo := struct {
		Shuffled bool
		Cards    []string
	}{
		Shuffled: shuffled,
		Cards:    cards,
	}
	mock.lockNewDeck.Lock()
	mock.calls.NewDeck = append(mock.calls.NewDeck, callInfo)
	mock.lockNewDeck.Unlock()
	if mock.NewDeckFunc == nil {
		var (
			deckOut *deck.Deck
			errOut  error
		)
		return deckOut, errOut
	}
	return mock.NewDeckFunc(shuffled, cards...)
}

// NewDeckCalls gets all the calls that were made to NewDeck.
// Check the length with:
//
//	len(mockedManager.NewDeckCalls())
func (mock *ManagerMock) NewDeckCalls() []struct {
	Shuffled bool
	Cards    []string
} {
	var calls []struct {
		Shuffled bool
		Cards    []string
	}
	mock.lockNewDeck.RLock()
	calls = mock.calls.NewDeck
	mock.lockNewDeck.RUnlock()
	return calls
}
